name: farmio-check
services:
  postgresql:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:16
    ports: 
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

